In [440]:
import pandas as pd
import numpy as np
import re

## Charger le CSV

In [441]:
url= "data/pokemon_dataset.csv"
# df = pd.read_csv(url, sep=";", encoding="utf-8")
df = pd.read_csv(url, sep=";", encoding="utf-8", index_col=0)
df

,0,1,2,3,4,5,6,7,8,9,...,790,791,792,793,794,795,796,797,798,799
#,635,606,58,479,61,560,317,442,690,411,...,419,113,554,16,639,65,98,250,390,94
Name,hydreigon,Beheeyem,Growlithe,RotomWash Rotom,Poliwhirl,SCRAFTY,Swalot,Spiritomb,skrelp,Bastiodon,...,FLOATZEL,CHANSEY,darumaka,Pidgey,Terrakion,ALAKAZAMMEGA ALAKAZAM,KRABBY,Ho-oh,chimchar,gengarmega gengar
Total,600,485,350,520,385,488,467,485,320,495,...,495,450,315,251,580,590,325,680,309,600
HP,92.0,75.0,55.0,50.0,65.0,NaN,100.0,50.0,50.0,60.0,...,85.0,250.0,70.0,40.0,91.0,55.0,30.0,106.0,NaN,60.0
Attack,105,75,70,65,65,90,73,92,60,52,...,105,5,90,45,129,NaN,105,130,58,NaN
Defense % of Attack,85.7143,100.0,64.2857,164.6154,100.0,127.7778,113.6986,117.3913,100.0,323.0769,...,52.381,100.0,50.0,88.8889,69.7674,130.0,85.7143,69.2308,75.8621,123.0769
Sp. Atk / Sp. Def,125 / 90,125 / 95,70 / 50,105 / 107,50 / 50,45 / 115,73 / 83,92 / 108,60 / 60,47 / 138,...,85 / 50,35 / 105,15 / 45,35 / 35,72 / 90,175 / 95,25 / 25,110 / 154,58 / 44,170 / 95
Speed,98.0,40.0,60.0,86.0,90.0,58.0,55.0,35.0,30.0,30.0,...,115.0,50.0,50.0,56.0,108.0,150.0,50.0,90.0,61.0,130.0
Generation,5.0,5.0,1.0,4.0,1.0,5.0,3.0,4.0,6.0,4.0,...,4.0,NaN,5.0,1.0,5.0,1.0,1.0,2.0,NaN,1.0
Legendary,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,True,False,False
Types,"Dark, Dragon","Psychic,","Fire,","Electric, Water","Water,","Dark, Fighting","Poison,","Ghost, Dark","Poison, Water","Rock, Steel",...,"Water,","Normal,","Fire,","Normal, Flying","Rock, Fighting","Psychic,","Water,","Fire, Flying","Fire,","Ghost, Poison"

## Transposee du dataframe

In [442]:
df = df.T
# df.columns = df.iloc[0]
# df = df.iloc[1:].reset_index(drop=True)
df

,#,Name,Total,HP,Attack,Defense % of Attack,Sp. Atk / Sp. Def,Speed,Generation,Legendary,Types
0,635,hydreigon,600,92.0,105,85.7143,125 / 90,98.0,5.0,False,"Dark, Dragon"
1,606,Beheeyem,485,75.0,75,100.0,125 / 95,40.0,5.0,False,"Psychic,"
2,58,Growlithe,350,55.0,70,64.2857,70 / 50,60.0,1.0,False,"Fire,"
3,479,RotomWash Rotom,520,50.0,65,164.6154,105 / 107,86.0,4.0,False,"Electric, Water"
4,61,Poliwhirl,385,65.0,65,100.0,50 / 50,90.0,1.0,False,"Water,"
...,...,...,...,...,...,...,...,...,...,...,...
795,65,ALAKAZAMMEGA ALAKAZAM,590,55.0,NaN,130.0,175 / 95,150.0,1.0,False,"Psychic,"
796,98,KRABBY,325,30.0,105,85.7143,25 / 25,50.0,1.0,False,"Water,"
797,250,Ho-oh,680,106.0,130,69.2308,110 / 154,90.0,2.0,True,"Fire, Flying"
798,390,chimchar,309,NaN,58,75.8621,58 / 44,61.0,NaN,False,"Fire,"
799,94,gengarmega gengar,600,60.0,NaN,123.0769,170 / 95,130.0,1.0,False,"Ghost, Poison"

## Fonction pour voir pokemon par id

In [443]:
def afficher_pokemon(df, num = []):
    display(df[df['#'].isin(num)])

## Fix les colonnes numeriques

In [444]:
# ATTENTION : avec cette fonction on va enlever le '-' ce qui va nous donner en quelques sortes
# la valeur absolue des nombres concernés
def regex_garder_numerique(df, columns=[]):
    for name in columns:
        df[name] = df[name].str.replace(r"[^0-9.]", "", regex=True)
    return df

df = regex_garder_numerique(df, ["HP", "Attack", "Defense % of Attack", "Speed", "Generation"])

## Changer les types des colonnes

In [445]:
colonnes_num = [
    "#", "Total", "HP", "Attack",
    "Defense % of Attack", "Speed", "Generation"
]

for col in colonnes_num:
    df[col] = pd.to_numeric(df[col], errors="raise")
    # erreurs = df[pd.to_numeric(df[col], errors="coerce").isna()][col]
    # if not erreurs.empty:
    #     print(f"\nColonne : {col}")
    #     print(erreurs.unique())

In [446]:
df.info()

<class 'pandas.DataFrame'>
Index: 800 entries, 0 to 799
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   #                    800 non-null    int64
 1   Name                 800 non-null    str
 2   Total                800 non-null    int64
 3   HP                   773 non-null    float64
 4   Attack               775 non-null    float64
 5   Defense % of Attack  800 non-null    float64
 6   Sp. Atk / Sp. Def    800 non-null    str
 7   Speed                757 non-null    float64
 8   Generation           761 non-null    float64
 9   Legendary            800 non-null    str
 10  Types                800 non-null    str
dtypes: float64(5), int64(2), str(4)
memory usage: 107.3+ KB

## Trier par # et fix "Generation"

In [447]:
df.sort_values("#", inplace=True)
df["Generation"] = pd.to_numeric(df["Generation"].ffill().bfill())
df

,#,Name,Total,HP,Attack,Defense % of Attack,Sp. Atk / Sp. Def,Speed,Generation,Legendary,Types
374,1,Bulbasaur,318,45.0,49.0,100.0000,65 / 65,45.0,1.0,False,"Grass, Poison"
729,2,Ivysaur,405,60.0,62.0,101.6129,80 / 80,60.0,1.0,False,"Grass, Poison"
151,3,venusaur,525,80.0,82.0,101.2195,100 / 100,80.0,1.0,False,"Grass, Poison"
325,3,VenusaurMega Venusaur,625,80.0,100.0,123.0000,122 / 120,80.0,1.0,False,"Grass, Poison"
672,4,CHARMANDER,309,39.0,52.0,82.6923,60 / 50,65.0,1.0,False,"Fire,"
...,...,...,...,...,...,...,...,...,...,...,...
38,719,DiancieMega Diancie,700,50.0,160.0,68.7500,160 / 110,110.0,6.0,True,"Rock, Fairy"
72,719,DIANCIE,600,50.0,100.0,150.0000,100 / 150,50.0,6.0,True,"Rock, Fairy"
156,720,HoopaHoopa Unbound,680,80.0,160.0,37.5000,170 / 130,80.0,6.0,True,"Psychic, Dark"
718,720,HoopaHoopa Confined,600,80.0,110.0,54.5455,150 / 130,70.0,6.0,True,"Psychic, Ghost"
406,721,Volcanion,600,80.0,110.0,109.0909,130 / 90,70.0,6.0,True,"Fire, Water"

## Gerer Noms

In [448]:
df["Name"] = df["Name"].str.title()
df

,#,Name,Total,HP,Attack,Defense % of Attack,Sp. Atk / Sp. Def,Speed,Generation,Legendary,Types
374,1,Bulbasaur,318,45.0,49.0,100.0000,65 / 65,45.0,1.0,False,"Grass, Poison"
729,2,Ivysaur,405,60.0,62.0,101.6129,80 / 80,60.0,1.0,False,"Grass, Poison"
151,3,Venusaur,525,80.0,82.0,101.2195,100 / 100,80.0,1.0,False,"Grass, Poison"
325,3,Venusaurmega Venusaur,625,80.0,100.0,123.0000,122 / 120,80.0,1.0,False,"Grass, Poison"
672,4,Charmander,309,39.0,52.0,82.6923,60 / 50,65.0,1.0,False,"Fire,"
...,...,...,...,...,...,...,...,...,...,...,...
38,719,Dianciemega Diancie,700,50.0,160.0,68.7500,160 / 110,110.0,6.0,True,"Rock, Fairy"
72,719,Diancie,600,50.0,100.0,150.0000,100 / 150,50.0,6.0,True,"Rock, Fairy"
156,720,Hoopahoopa Unbound,680,80.0,160.0,37.5000,170 / 130,80.0,6.0,True,"Psychic, Dark"
718,720,Hoopahoopa Confined,600,80.0,110.0,54.5455,150 / 130,70.0,6.0,True,"Psychic, Ghost"
406,721,Volcanion,600,80.0,110.0,109.0909,130 / 90,70.0,6.0,True,"Fire, Water"

## Supprimer doublons

In [449]:
print(df.shape)
df = df.drop_duplicates()
print(df.shape)

(800, 11)
(800, 11)

In [450]:
df

,#,Name,Total,HP,Attack,Defense % of Attack,Sp. Atk / Sp. Def,Speed,Generation,Legendary,Types
374,1,Bulbasaur,318,45.0,49.0,100.0000,65 / 65,45.0,1.0,False,"Grass, Poison"
729,2,Ivysaur,405,60.0,62.0,101.6129,80 / 80,60.0,1.0,False,"Grass, Poison"
151,3,Venusaur,525,80.0,82.0,101.2195,100 / 100,80.0,1.0,False,"Grass, Poison"
325,3,Venusaurmega Venusaur,625,80.0,100.0,123.0000,122 / 120,80.0,1.0,False,"Grass, Poison"
672,4,Charmander,309,39.0,52.0,82.6923,60 / 50,65.0,1.0,False,"Fire,"
...,...,...,...,...,...,...,...,...,...,...,...
38,719,Dianciemega Diancie,700,50.0,160.0,68.7500,160 / 110,110.0,6.0,True,"Rock, Fairy"
72,719,Diancie,600,50.0,100.0,150.0000,100 / 150,50.0,6.0,True,"Rock, Fairy"
156,720,Hoopahoopa Unbound,680,80.0,160.0,37.5000,170 / 130,80.0,6.0,True,"Psychic, Dark"
718,720,Hoopahoopa Confined,600,80.0,110.0,54.5455,150 / 130,70.0,6.0,True,"Psychic, Ghost"
406,721,Volcanion,600,80.0,110.0,109.0909,130 / 90,70.0,6.0,True,"Fire, Water"

## Reset index

In [451]:
df = df.reset_index(drop=True)
df.columns.name = "index"
df.head()

index,#,Name,Total,HP,Attack,Defense % of Attack,Sp. Atk / Sp. Def,Speed,Generation,Legendary,Types
0,1,Bulbasaur,318,45.0,49.0,100.0000,65 / 65,45.0,1.0,False,"Grass, Poison"
1,2,Ivysaur,405,60.0,62.0,101.6129,80 / 80,60.0,1.0,False,"Grass, Poison"
2,3,Venusaur,525,80.0,82.0,101.2195,100 / 100,80.0,1.0,False,"Grass, Poison"
3,3,Venusaurmega Venusaur,625,80.0,100.0,123.0000,122 / 120,80.0,1.0,False,"Grass, Poison"
4,4,Charmander,309,39.0,52.0,82.6923,60 / 50,65.0,1.0,False,"Fire,"

## Split Sp. Atk / Sp. Def

Cette facon de faire va poser un problème car on ne gère pas les lignes qui ont 3 valeurs dans Sp. Atk / Sp. Def. Cela va nous conduire ensuite a les remplacer par des nan ce qui va apauvrir notre base de données

In [452]:
# split_cols = df['Sp. Atk / Sp. Def'].astype(str).str.split('/', n=1, expand=True)
# df['Sp. Atk'] = split_cols[0].str.strip()
# df['Sp. Def'] = split_cols[1].str.strip()

# df.drop(columns=['Sp. Atk / Sp. Def'], inplace=True)
# df.head()

### Bonne facon de faire en changeant a la main les deux lignes problématiques

In [453]:
# # Pour trouver les lignes problématiques
# split = df["Sp. Atk / Sp. Def"].str.split("/", expand=True)
# print(split.shape)

In [454]:
# # Si le nombre de colonnes est différent de 2, jecherche les valeurs anormales :
# df[df["Sp. Atk / Sp. Def"].str.count("/") != 1]["Sp. Atk / Sp. Def"]
# erreurs = df[df["Sp. Atk / Sp. Def"].str.count("/") != 1]
# print(erreurs)

In [455]:
# # faut corriger d'abord
# df.loc[789, "Sp. Atk / Sp. Def"] = "44 / 46"
# df.loc[115 , "Sp. Atk / Sp. Def"] = "35 / 110" 
# split = df["Sp. Atk / Sp. Def"].str.split("/", expand=True)

# print(split.shape)
# print(split.columns)
# nb = df["Sp. Atk / Sp. Def"].str.split("/").str.len()

# print(df.loc[nb != 2, "Sp. Atk / Sp. Def"])

In [456]:
# # nettoyage de données, la meilleure pratique est de les séparer en deux colonnes numériques.
# df[["Sp. Atk", "Sp. Def"]] = df["Sp. Atk / Sp. Def"].str.split("/", expand=True)
# #J' enleve les espaces et convertir en nombres :
# df["Sp. Def"] = pd.to_numeric(df["Sp. Def"].str.strip())
# df["Sp. Atk"] = pd.to_numeric(df["Sp. Atk"].str.strip())

# # Ensuite, je supprime l'ancienne colonne :
# df = df.drop(columns=["Sp. Atk / Sp. Def"])
# df.head()

In [457]:
# afficher_pokemon(df, [107,713])

### Autre bonne facon de faire avec la regex

In [458]:
df["Sp. Atk / Sp. Def"] = (
    df["Sp. Atk / Sp. Def"]
    .str.replace("//", "/", regex=False)
    .str.replace(r"\s+", " ", regex=True)
)

df["Sp. Atk / Sp. Def"] = df["Sp. Atk / Sp. Def"].str.replace(
    r"^\s*(\d+)\s*/\s*(\d+)\s*/\s*\d+\s*$",
    r"\1 / \2",
    regex=True
)

df_sp_atk = df["Sp. Atk / Sp. Def"].str.split(" / ", expand=True)[0]
df_sp_def = df["Sp. Atk / Sp. Def"].str.split(" / ", expand=True)[1]

index_sp_atk_def = df.columns.get_loc("Sp. Atk / Sp. Def")

df.insert(index_sp_atk_def + 1, "Sp. Atk", df_sp_atk)
df.insert(index_sp_atk_def + 2, "Sp. Def", df_sp_def)
df.head()

index,#,Name,Total,HP,Attack,Defense % of Attack,Sp. Atk / Sp. Def,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Types
0,1,Bulbasaur,318,45.0,49.0,100.0000,65 / 65,65,65,45.0,1.0,False,"Grass, Poison"
1,2,Ivysaur,405,60.0,62.0,101.6129,80 / 80,80,80,60.0,1.0,False,"Grass, Poison"
2,3,Venusaur,525,80.0,82.0,101.2195,100 / 100,100,100,80.0,1.0,False,"Grass, Poison"
3,3,Venusaurmega Venusaur,625,80.0,100.0,123.0000,122 / 120,122,120,80.0,1.0,False,"Grass, Poison"
4,4,Charmander,309,39.0,52.0,82.6923,60 / 50,60,50,65.0,1.0,False,"Fire,"

In [459]:
afficher_pokemon(df, [107,713])

index,#,Name,Total,HP,Attack,Defense % of Attack,Sp. Atk / Sp. Def,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Types
115,107,Hitmonchan,455,50.0,105.0,75.2381,35 / 110,35,110,76.0,1.0,False,"Fighting,"
789,713,Avalugg,514,95.0,117.0,157.2650,44 / 46,44,46,28.0,6.0,False,"Ice,"

## Fix Defense %

In [460]:
df.head()

index,#,Name,Total,HP,Attack,Defense % of Attack,Sp. Atk / Sp. Def,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Types
0,1,Bulbasaur,318,45.0,49.0,100.0000,65 / 65,65,65,45.0,1.0,False,"Grass, Poison"
1,2,Ivysaur,405,60.0,62.0,101.6129,80 / 80,80,80,60.0,1.0,False,"Grass, Poison"
2,3,Venusaur,525,80.0,82.0,101.2195,100 / 100,100,100,80.0,1.0,False,"Grass, Poison"
3,3,Venusaurmega Venusaur,625,80.0,100.0,123.0000,122 / 120,122,120,80.0,1.0,False,"Grass, Poison"
4,4,Charmander,309,39.0,52.0,82.6923,60 / 50,60,50,65.0,1.0,False,"Fire,"

In [461]:
df["Defense"] = (
    df["Defense % of Attack"] * df["Attack"] / 100
).round()
df.head()

index,#,Name,Total,HP,Attack,Defense % of Attack,Sp. Atk / Sp. Def,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Types,Defense
0,1,Bulbasaur,318,45.0,49.0,100.0000,65 / 65,65,65,45.0,1.0,False,"Grass, Poison",49.0
1,2,Ivysaur,405,60.0,62.0,101.6129,80 / 80,80,80,60.0,1.0,False,"Grass, Poison",63.0
2,3,Venusaur,525,80.0,82.0,101.2195,100 / 100,100,100,80.0,1.0,False,"Grass, Poison",83.0
3,3,Venusaurmega Venusaur,625,80.0,100.0,123.0000,122 / 120,122,120,80.0,1.0,False,"Grass, Poison",123.0
4,4,Charmander,309,39.0,52.0,82.6923,60 / 50,60,50,65.0,1.0,False,"Fire,",43.0

## Valeurs manquantes

In [462]:
df.isna().sum()

index
#                       0
Name                    0
Total                   0
HP                     27
Attack                 25
Defense % of Attack     0
Sp. Atk / Sp. Def       0
Sp. Atk                 0
Sp. Def                 0
Speed                  43
Generation              0
Legendary               0
Types                   0
Defense                25
dtype: int64

In [463]:
df["Sp. Atk"] = df["Sp. Atk"].astype(float)
df["Sp. Def"] = df["Sp. Def"].astype(float)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   #                    800 non-null    int64
 1   Name                 800 non-null    str
 2   Total                800 non-null    int64
 3   HP                   773 non-null    float64
 4   Attack               775 non-null    float64
 5   Defense % of Attack  800 non-null    float64
 6   Sp. Atk / Sp. Def    800 non-null    str
 7   Sp. Atk              800 non-null    float64
 8   Sp. Def              800 non-null    float64
 9   Speed                757 non-null    float64
 10  Generation           800 non-null    float64
 11  Legendary            800 non-null    str
 12  Types                800 non-null    str
 13  Defense              775 non-null    float64
dtypes: float64(8), int64(2), str(4)
memory usage: 87.6 KB

### HP manquants

In [464]:
display(df[(df["HP"] > df["Total"]) | (df["Attack"] > df["Total"]) | (df["Speed"] > df["Total"] ) | (df["Sp. Atk"] > df["Total"] ) | (df["Sp. Def"] > df["Total"] )])
df.loc[df["HP"] > df["Total"], "HP"] = np.nan

display(df[(df["HP"] > df["Total"]) | (df["Attack"] > df["Total"]) | (df["Speed"] > df["Total"]) | (df["Sp. Atk"] > df["Total"] ) | (df["Sp. Def"] > df["Total"] )])


#display(df.loc[df["Id"] == 15])
print(df.isna().sum())

index,#,Name,Total,HP,Attack,Defense % of Attack,Sp. Atk / Sp. Def,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Types,Defense
18,15,Beedrill,395,15925.0,90.0,44.4444,45 / 80,45.0,80.0,75.0,1.0,False,"Bug, Poison",40.0
374,342,Crawdaunt,468,15435.0,120.0,70.8333,90 / 55,90.0,55.0,55.0,3.0,False,"Water, Dark",85.0
411,375,Metang,420,14700.0,75.0,133.3333,55 / 80,55.0,80.0,50.0,3.0,False,"Steel, Psychic",100.0
536,479,Rotomfan Rotom,520,12250.0,65.0,164.6154,105 / 107,105.0,107.0,NaN,4.0,False,"Electric, Flying",107.0
643,582,Vanillite,305,8820.0,50.0,100.0000,65 / 60,65.0,60.0,NaN,5.0,False,"Ice,",50.0
645,584,Vanilluxe,535,17395.0,95.0,89.4737,110 / 95,110.0,95.0,79.0,5.0,False,"Ice,",85.0

Empty DataFrame
Columns: [#, Name, Total, HP, Attack, Defense % of Attack, Sp. Atk / Sp. Def, Sp. Atk, Sp. Def, Speed, Generation, Legendary, Types, Defense]
Index: []

index
#                       0
Name                    0
Total                   0
HP                     33
Attack                 25
Defense % of Attack     0
Sp. Atk / Sp. Def       0
Sp. Atk                 0
Sp. Def                 0
Speed                  43
Generation              0
Legendary               0
Types                   0
Defense                25
dtype: int64

In [465]:
# Cas deja géré plus haut avec la regex qui enleve les "-"
# display(df.head())
# colonnes = ["Total", "HP", "Defense % of Attack", "Sp. Atk", "Sp. Def", "Speed"]
# display(df[(df[colonnes] < 0).any(axis=1)])
# df["HP"] = df["HP"].abs() # pour mettre la colonne en valeur absolue
# df

In [466]:
df.fillna({
    "HP": df["Total"] - (df["Attack"] + df["Defense"] + df["Sp. Atk"] + df["Sp. Def"] + df["Speed"] )
}, inplace= True)
df.isna().sum()

index
#                       0
Name                    0
Total                   0
HP                      5
Attack                 25
Defense % of Attack     0
Sp. Atk / Sp. Def       0
Sp. Atk                 0
Sp. Def                 0
Speed                  43
Generation              0
Legendary               0
Types                   0
Defense                25
dtype: int64

### Speed manquants

In [467]:
df.fillna({
    "Speed": df["Total"] - (df["Attack"] + df["Defense"] + df["Sp. Atk"] + df["Sp. Def"] + df["HP"] )
}, inplace= True)
df.isna().sum()

index
#                       0
Name                    0
Total                   0
HP                      5
Attack                 25
Defense % of Attack     0
Sp. Atk / Sp. Def       0
Sp. Atk                 0
Sp. Def                 0
Speed                   4
Generation              0
Legendary               0
Types                   0
Defense                25
dtype: int64

In [468]:
df.isna().sum()

index
#                       0
Name                    0
Total                   0
HP                      5
Attack                 25
Defense % of Attack     0
Sp. Atk / Sp. Def       0
Sp. Atk                 0
Sp. Def                 0
Speed                   4
Generation              0
Legendary               0
Types                   0
Defense                25
dtype: int64

### Cas de plusieurs nan par ligne (sauf les Attack Defense qui manquent)

In [469]:
stats = ["HP", "Attack", "Defense", "Sp. Atk", "Sp. Def", "Speed"]

def calculer_statistiques_multiple_nan(df, stats, df_ratio):
    masque = df[stats].isna().sum(axis=1) > 1
    print("========== masque ==========")
    print(masque)
    reste = df.loc[masque, "Total"] - df.loc[masque, stats].sum(axis=1)
    print("========== reste ==========")
    print(reste)
        
    ratios = df_ratio.loc[df.loc[masque, "Types"]]
    print("========== ratios ==========")
    print(ratios)

    ratios.index = df.loc[masque].index
    print("========== ratios ==========")
    print(ratios)

    ratios_nan = ratios.where(df.loc[masque, stats].isna())
    print("========== ratios_nan ==========")
    print(ratios_nan)

    nouveaux_ratios = ratios_nan.div(ratios_nan.sum(axis=1), axis=0)
    print("========== nouveaux_ratios ==========")
    print(nouveaux_ratios)
    
    nouvelles_stats = nouveaux_ratios.mul(reste, axis=0)
    print("========== nouvelles_stats ==========")
    print(nouvelles_stats)

    df.loc[masque, stats] = df.loc[masque, stats].fillna(nouvelles_stats.round())

    return df

moyennes_stats = df.groupby(["Types"])[stats].mean()
moyennes_total = df.groupby(["Types"])["Total"].mean()

print(moyennes_stats)
print(moyennes_total)

df_ratio = pd.DataFrame(index=moyennes_stats.index)
df_ratio["HP"] = moyennes_stats["HP"] / moyennes_total
df_ratio["Attack + Defense"] = ((moyennes_stats["Attack"] + moyennes_stats["Defense"]) / moyennes_total)
df_ratio["Sp. Atk"] = moyennes_stats["Sp. Atk"] / moyennes_total
df_ratio["Sp. Def"] = moyennes_stats["Sp. Def"] / moyennes_total
df_ratio["Speed"] = moyennes_stats["Speed"] / moyennes_total

print(df_ratio)

df["Attack + Defense"] = (df["Attack"] + df["Defense"]).where(df["Attack"].notna() & df["Defense"].notna())
new_stats = ["HP", "Attack + Defense", "Sp. Atk", "Sp. Def", "Speed"]

df = calculer_statistiques_multiple_nan(df, new_stats, df_ratio)

index                  HP      Attack     Defense     Sp. Atk     Sp. Def  \
Types
Bug,            53.058824   50.352941   55.411765   39.294118   43.647059
Bug, Electric   60.000000   62.000000   55.000000   77.000000   55.000000
Bug, Fighting   80.000000  155.000000   95.000000   40.000000  100.000000
Bug, Fire       70.000000   72.500000   60.000000   92.500000   80.000000
Bug, Flying     63.000000   70.142857   61.571429   72.857143   69.071429
...                   ...         ...         ...         ...         ...
Water, Ice      90.000000   83.333333  113.333333   80.000000   78.333333
Water, Poison   61.666667   68.333333   58.333333   61.666667   91.666667
Water, Psychic  87.000000   73.000000  104.000000   94.000000   79.000000
Water, Rock     70.750000   82.750000  112.750000   61.500000   65.000000
Water, Steel    84.000000   86.000000   88.000000  111.000000  101.000000

index               Speed
Types
Bug,            47.941176
Bug, Electric   86.500000
Bug, Fighting   80.000000
Bug, Fire       80.000000
Bug, Flying     82.857143
...                   ...
Water, Ice      66.666667
Water, Poison   85.000000
Water, Psychic  44.000000
Water, Rock     36.000000
Water, Steel    60.000000

[154 rows x 6 columns]
Types
Bug,              289.705882
Bug, Electric     395.500000
Bug, Fighting     550.000000
Bug, Fire         455.000000
Bug, Flying       419.500000
                     ...
Water, Ice        511.666667
Water, Poison     426.666667
Water, Psychic    481.000000
Water, Rock       428.750000
Water, Steel      530.000000
Name: Total, Length: 154, dtype: float64
                      HP  Attack + Defense   Sp. Atk   Sp. Def     Speed
Types
Bug,            0.183147          0.365076  0.135635  0.150660  0.165482
Bug, Electric   0.151707          0.295828  0.194690  0.139064  0.218710
Bug, Fighting   0.145455          0.454545  0.072727  0.181818  0.145455
Bug, Fire       0.153846          0.291209  0.203297  0.175824  0.175824
Bug, Flying     0.150179          0.313979  0.173676  0.164652  0.197514
...                  ...               ...       ...       ...       ...
Water, Ice      0.175896          0.384365  0.156352  0.153094  0.130293
Water, Poison   0.144531          0.296875  0.144531  0.214844  0.199219
Water, Psychic  0.180873          0.367983  0.195426  0.164241  0.091476
Water, Rock     0.165015          0.455977  0.143440  0.151603  0.083965
Water, Steel    0.158491          0.328302  0.209434  0.190566  0.113208

[154 rows x 5 columns]
========== masque ==========
0      False
1      False
2      False
3      False
4      False
       ...
795    False
796    False
797    False
798    False
799    False
Length: 800, dtype: bool
========== reste ==========
181     70.0
359    190.0
536    136.0
559    175.0
643     80.0
dtype: float64
========== ratios ==========
                        HP  Attack + Defense   Sp. Atk   Sp. Def     Speed
Types
Bug, Poison       0.158084          0.363353  0.122156  0.170539  0.198846
Ground,           0.167834          0.436454  0.120864  0.140911  0.143441
Electric, Flying  0.140904          0.313244  0.213914  0.155134  0.192987
Fire, Fighting    0.152174          0.352464  0.196232  0.131304  0.161981
Ice,              0.158395          0.349560  0.178837  0.184878  0.137263
========== ratios ==========
           HP  Attack + Defense   Sp. Atk   Sp. Def     Speed
181  0.158084          0.363353  0.122156  0.170539  0.198846
359  0.167834          0.436454  0.120864  0.140911  0.143441
536  0.140904          0.313244  0.213914  0.155134  0.192987
559  0.152174          0.352464  0.196232  0.131304  0.161981
643  0.158395          0.349560  0.178837  0.184878  0.137263
========== ratios_nan ==========
           HP  Attack + Defense  Sp. Atk  Sp. Def     Speed
181  0.158084               NaN      NaN      NaN  0.198846
359  0.167834          0.436454      NaN      NaN       NaN
536  0.140904               NaN      NaN      NaN  0.192987
559  0.152174               NaN      NaN      NaN  0.161981
643  0.158395               NaN      NaN      NaN  0.137263
========== nouveaux_ratios ==========
           HP  Attack + Defense  Sp. Atk  Sp. Def     Speed
181  0.442899               NaN      NaN      NaN  0.557101
359  0.277739          0.722261      NaN      NaN       NaN
536  0.422006               NaN      NaN      NaN  0.577994
559  0.484392               NaN      NaN      NaN  0.515608
643  0.535737               NaN      NaN      NaN  0.464263
========== nouvelles_stats ==========
            HP  Attack + Defense  Sp. Atk  Sp. Def      Speed
181  31.002928               NaN      NaN      NaN  38.997072
359  52.770412        137.229588      NaN      NaN        NaN
536  57.392758               NaN      NaN      NaN  78.607242
559  84.768568               NaN      NaN      NaN  90.231432
643  42.858950               NaN      NaN      NaN  37.141050

In [470]:
df.isna().sum()

index
#                       0
Name                    0
Total                   0
HP                      0
Attack                 25
Defense % of Attack     0
Sp. Atk / Sp. Def       0
Sp. Atk                 0
Sp. Def                 0
Speed                   0
Generation              0
Legendary               0
Types                   0
Defense                25
Attack + Defense       24
dtype: int64

### Cas special : Attack et Defense qui manquent

- x = Attack
- y = Defense
- x + y = Total - sum_stats_no_attack
- def = Defense % of Attack/100
- y = x * def
- x + x*def = Total - sum_stats_no_attack
- 1x + def*x = Total - sum_stats_no_attack
- (1 + def) * x = Total - sum_stats_no_attack
- x = (Total - sum_stats_no_attack) / (1 + def)

In [471]:
stats_no_attack = ['HP', 'Speed', 'Sp. Atk', 'Sp. Def']
missing_atk = ((df['Total'] - df[stats_no_attack].sum(axis=1)) / (1+df['Defense % of Attack']/100)).round()
df['Attack'] = df['Attack'].fillna(missing_atk)

In [472]:
df.isna().sum()

index
#                       0
Name                    0
Total                   0
HP                      0
Attack                  0
Defense % of Attack     0
Sp. Atk / Sp. Def       0
Sp. Atk                 0
Sp. Def                 0
Speed                   0
Generation              0
Legendary               0
Types                   0
Defense                25
Attack + Defense       24
dtype: int64

### Defense manquantes

In [473]:
df["Defense"] = (
    df["Defense % of Attack"] * df["Attack"] / 100
).round()
df.isna().sum()

index
#                       0
Name                    0
Total                   0
HP                      0
Attack                  0
Defense % of Attack     0
Sp. Atk / Sp. Def       0
Sp. Atk                 0
Sp. Def                 0
Speed                   0
Generation              0
Legendary               0
Types                   0
Defense                 0
Attack + Defense       24
dtype: int64

### drop Attack + Defense

In [474]:
df.drop(columns=["Attack + Defense"], inplace=True)

## fix lignes problematiques restantes

In [475]:
df.head()

index,#,Name,Total,HP,Attack,Defense % of Attack,Sp. Atk / Sp. Def,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Types,Defense
0,1,Bulbasaur,318,45.0,49.0,100.0000,65 / 65,65.0,65.0,45.0,1.0,False,"Grass, Poison",49.0
1,2,Ivysaur,405,60.0,62.0,101.6129,80 / 80,80.0,80.0,60.0,1.0,False,"Grass, Poison",63.0
2,3,Venusaur,525,80.0,82.0,101.2195,100 / 100,100.0,100.0,80.0,1.0,False,"Grass, Poison",83.0
3,3,Venusaurmega Venusaur,625,80.0,100.0,123.0000,122 / 120,122.0,120.0,80.0,1.0,False,"Grass, Poison",123.0
4,4,Charmander,309,39.0,52.0,82.6923,60 / 50,60.0,50.0,65.0,1.0,False,"Fire,",43.0

In [476]:
stats = ['HP', 'Speed', 'Sp. Atk', 'Sp. Def', "Attack", "Defense"]

df[abs(df["Total"] - df[stats].sum(axis=1)) > 0.001] #[stats].sum(axis=1)

index,#,Name,Total,HP,Attack,Defense % of Attack,Sp. Atk / Sp. Def,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Types,Defense
359,328,Trapinch,290,53.0,94.0,45.0000,45 / 45,45.0,45.0,10.0,3.0,False,"Ground,",42.0
455,410,Shieldon,350,30.0,110.0,280.9524,42 / 88,42.0,88.0,30.0,4.0,False,"Rock, Steel",309.0

In [477]:
stats = ["HP", "Attack", "Defense", "Sp. Atk", "Sp. Def", "Speed"]
display(df[df[stats].sum(axis=1) != df["Total"]])

df.loc[df[stats].sum(axis=1) != df["Total"], "Attack"] = np.nan
df.loc[df[stats].sum(axis=1) != df["Total"], "Defense"] = np.nan
df.loc[df[stats].sum(axis=1) != df["Total"], "Defense % of Attack"] = np.nan

# display(df[df["#"] == 410])
afficher_pokemon(df, num = [410, 328])

## Calcule la moyenne "Attack" et "Defense" par rapport "Generation"
df_mean = df.groupby("Generation")[["Attack", "Defense"]].agg("mean").round(2)
df_mean["Attack Percent"] = (df_mean["Attack"] / (df_mean["Defense"]+df_mean["Attack"])).round(2)
df_mean["Defense Percent"] = (df_mean["Defense"] / (df_mean["Defense"]+df_mean["Attack"])).round(2)
display(df_mean)

Attack_Defense = df["Total"] - df[["HP", "Sp. Atk", "Sp. Def", "Speed"]].sum(axis=1)
df.fillna({
    "Attack": (df["Generation"].map(df_mean["Attack Percent"]) * Attack_Defense).round(0),
    "Defense": (df["Generation"].map(df_mean["Defense Percent"]) * Attack_Defense).round(0),
}, inplace=True)

# display(df[df["#"] == 410])
afficher_pokemon(df, num = [410, 328])

## ReCalculer le pourcentage de Defense par rapport a l'Attack et Defense de nouvelle valeur: (defe/atta)*100 = defe%
df.fillna({
    "Defense % of Attack": (df["Defense"] / df["Attack"]) * 100
}, inplace=True)

# display(df[df["#"] == 410])
afficher_pokemon(df, num = [410, 328])

index,#,Name,Total,HP,Attack,Defense % of Attack,Sp. Atk / Sp. Def,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Types,Defense
359,328,Trapinch,290,53.0,94.0,45.0000,45 / 45,45.0,45.0,10.0,3.0,False,"Ground,",42.0
455,410,Shieldon,350,30.0,110.0,280.9524,42 / 88,42.0,88.0,30.0,4.0,False,"Rock, Steel",309.0

index,#,Name,Total,HP,Attack,Defense % of Attack,Sp. Atk / Sp. Def,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Types,Defense
359,328,Trapinch,290,53.0,NaN,NaN,45 / 45,45.0,45.0,10.0,3.0,False,"Ground,",NaN
455,410,Shieldon,350,30.0,NaN,NaN,42 / 88,42.0,88.0,30.0,4.0,False,"Rock, Steel",NaN

index       Attack  Defense  Attack Percent  Defense Percent
Generation
1.0          76.47    70.83            0.52             0.48
2.0          72.25    73.47            0.50             0.50
3.0          81.47    74.29            0.52             0.48
4.0          83.29    77.86            0.52             0.48
5.0          82.07    72.33            0.53             0.47
6.0          75.80    76.68            0.50             0.50

index,#,Name,Total,HP,Attack,Defense % of Attack,Sp. Atk / Sp. Def,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Types,Defense
359,328,Trapinch,290,53.0,71.0,NaN,45 / 45,45.0,45.0,10.0,3.0,False,"Ground,",66.0
455,410,Shieldon,350,30.0,83.0,NaN,42 / 88,42.0,88.0,30.0,4.0,False,"Rock, Steel",77.0

index,#,Name,Total,HP,Attack,Defense % of Attack,Sp. Atk / Sp. Def,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Types,Defense
359,328,Trapinch,290,53.0,71.0,92.957746,45 / 45,45.0,45.0,10.0,3.0,False,"Ground,",66.0
455,410,Shieldon,350,30.0,83.0,92.771084,42 / 88,42.0,88.0,30.0,4.0,False,"Rock, Steel",77.0

In [478]:
df[abs(df["Total"] - df[stats].sum(axis=1)) > 0.001]

Empty DataFrame
Columns: [#, Name, Total, HP, Attack, Defense % of Attack, Sp. Atk / Sp. Def, Sp. Atk, Sp. Def, Speed, Generation, Legendary, Types, Defense]
Index: []

In [479]:
df.isna().sum()

index
#                      0
Name                   0
Total                  0
HP                     0
Attack                 0
Defense % of Attack    0
Sp. Atk / Sp. Def      0
Sp. Atk                0
Sp. Def                0
Speed                  0
Generation             0
Legendary              0
Types                  0
Defense                0
dtype: int64

In [480]:
df.describe()

index,#,Total,HP,Attack,Defense % of Attack,Sp. Atk,Sp. Def,Speed,Generation,Defense
count,800.000000,800.00000,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000
mean,362.813750,435.10250,69.243750,79.01625,105.324802,72.820000,71.902500,68.302500,3.320000,73.817500
std,208.343798,119.96304,25.491353,32.42399,92.141481,32.722294,27.828916,29.061387,1.662394,31.129053
min,1.000000,180.00000,1.000000,5.00000,11.111100,10.000000,20.000000,5.000000,1.000000,5.000000
25%,184.750000,330.00000,50.000000,55.00000,70.636200,49.750000,50.000000,45.000000,2.000000,50.000000
50%,364.500000,450.00000,65.000000,75.00000,92.907423,65.000000,70.000000,65.000000,3.000000,70.000000
75%,539.250000,515.00000,80.000000,100.00000,120.498400,95.000000,90.000000,90.000000,5.000000,90.000000
max,721.000000,780.00000,255.000000,190.00000,2300.000000,194.000000,230.000000,180.000000,6.000000,230.000000

In [481]:
df[df["Defense % of Attack"] == 2300.0]

index,#,Name,Total,HP,Attack,Defense % of Attack,Sp. Atk / Sp. Def,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Types,Defense
230,213,Shuckle,505,20.0,10.0,2300.0,10 / 230,10.0,230.0,5.0,2.0,False,"Bug, Rock",230.0

In [485]:
df

index,#,Name,Total,HP,Attack,Defense % of Attack,Sp. Atk / Sp. Def,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Types,Defense
0,1,Bulbasaur,318,45.0,49.0,100.0000,65 / 65,65.0,65.0,45.0,1.0,False,"Grass, Poison",49.0
1,2,Ivysaur,405,60.0,62.0,101.6129,80 / 80,80.0,80.0,60.0,1.0,False,"Grass, Poison",63.0
2,3,Venusaur,525,80.0,82.0,101.2195,100 / 100,100.0,100.0,80.0,1.0,False,"Grass, Poison",83.0
3,3,Venusaurmega Venusaur,625,80.0,100.0,123.0000,122 / 120,122.0,120.0,80.0,1.0,False,"Grass, Poison",123.0
4,4,Charmander,309,39.0,52.0,82.6923,60 / 50,60.0,50.0,65.0,1.0,False,"Fire,",43.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Dianciemega Diancie,700,50.0,160.0,68.7500,160 / 110,160.0,110.0,110.0,6.0,True,"Rock, Fairy",110.0
796,719,Diancie,600,50.0,100.0,150.0000,100 / 150,100.0,150.0,50.0,6.0,True,"Rock, Fairy",150.0
797,720,Hoopahoopa Unbound,680,80.0,160.0,37.5000,170 / 130,170.0,130.0,80.0,6.0,True,"Psychic, Dark",60.0
798,720,Hoopahoopa Confined,600,80.0,110.0,54.5455,150 / 130,150.0,130.0,70.0,6.0,True,"Psychic, Ghost",60.0
799,721,Volcanion,600,80.0,110.0,109.0909,130 / 90,130.0,90.0,70.0,6.0,True,"Fire, Water",120.0